# Generated by Django 2.2.7 on 2020-05-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200502_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='title',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
