# Generated by Django 2.2.7 on 2020-05-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200502_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='TimeofUpload',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='filecover',
            field=models.FileField(blank=True, null=True, upload_to='filecovers/'),
        ),
    ]
