# Generated by Django 2.2.7 on 2020-05-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200504_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tax',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
