# Generated by Django 2.2.7 on 2020-05-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_person_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='email',
            new_name='GSTN',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='location',
            new_name='INVOICEDATE',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='tax',
            new_name='MonthofPayment',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='RIN',
        ),
        migrations.AddField(
            model_name='person',
            name='TOTALGST',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
