# Generated by Django 2.2.7 on 2020-05-06 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200506_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='INVOICEDATE',
        ),
    ]
