# Generated by Django 2.2.7 on 2020-05-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_person_invoicedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='GSTN',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
