# Generated by Django 2.2.7 on 2020-05-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200506_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='RIN',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
